version: '3'
services:
  datadomain-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-datadomain-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_datadomain_api:/usr/lib/python3.6/site-packages/vlab_datadomain_api
    command: ["python3", "app.py"]

  datadomain-worker:
    image:
      willnx/vlab-datadomain-worker
    volumes:
      - ./vlab_datadomain_api:/usr/lib/python3.6/site-packages/vlab_datadomain_api
      - /mnt/raid/images/datadomain:/images:ro
    environment:
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  datadomain-broker:
    image:
      rabbitmq:3.7-alpine
